---
name: "Test application"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  testApp:
    name: "Run tests"
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Check for vulnerabilities
        run: npm audit

      - name: Execute tests
        run: npm test

      - name: Publish test execution report
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: "Test execution report"
          path: "./testReport.html"

      - name: Publish test coverage report
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: "Test coverage report"
          path: "./coverage"